# This file was generated by 'rake generate_secret',
# and should not be made visible to public.
# If you have a load-balancing Redmine cluster, you will need to use the
# same version of this file on each machine. And be sure to restart your
# server when you modify this file.

# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
ChiliProject::Application.config.secret_token = 'df6bb8a38837609d7f9dcb1ede43de6720b8d73256bf2576fa0198fb5c652f63d416a1ccef687698'
